Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,7 +36,12 @@ jobs:
         run: |
           ENDPOINT='frontend/o2switch/o2switch-ssh-whitelist/index.live.php'
           echo "Testing connectivity to the server..."
-          curl -I https://$SERVER:2083
+          CONNECTIVITY_CHECK=$(curl -I https://$SERVER:2083)
+          echo "Connectivity Check: $CONNECTIVITY_CHECK"
+          if [[ $CONNECTIVITY_CHECK != *"200 OK"* ]]; then
+            echo "Error: Unable to connect to the server."
+            exit 60
+          fi
           echo "Getting actual whitelisted IPs..."
           RESPONSE=$(curl -sX GET "https://$LOGIN:$PASSWORD@$SERVER:2083/$ENDPOINT?r=list")
           echo "Full Response: $RESPONSE"
